### PR TITLE
Clean up TREC

### PR DESCRIPTION
**Pull request by arnaudstiegler**
- Addressed comments in the spreadsheet
- added answer-choices everywhere
- added original task ticks
- added prompts for original task
- added metrics

### CODE REVIEW

**Comment by stephenbach** [comment]
It's probably not a huge deal since we won't evaluate on them, but it would be good for the answer_choices to be only the ones actually listed in the choices for the prompt. So for the fine grain classification, it should be just the options with a map from the label (over all the choices) to the entry in answer_choices.

**Comment by arnaudstiegler** [comment]
Will update them

**Comment by arnaudstiegler** [comment]
@stephenbach should be good now. I added a mapping from fine_label to the fined grained categories

**Review by stephenbach — APPROVED** [review]
LGTM! Thanks!

**Pull request merged**
