### PR TITLE
adding prompts for freebase_qa

### PR DESCRIPTION
**Pull request by rteehas**
Added prompt templates

### CODE REVIEW

**Comment by stephenbach** [comment]
Thanks!

I'm wondering about these inference chain prompts. The output might be easier for the model to generate and less sensitive to vocab if we made the output more natural.
```
Prompt + X

What chain of relations between topic entity and answer could be used to solve the following question:

The final of which sport at the 1900 Olympics in Paris attracted 6,000 spectators, the largest crowd at any event at that Olympics?

Y

olympics, olympic games, sports
```

**Comment by rteehas** [comment]
> Thanks!
> 
> I'm wondering about these inference chain prompts. The output might be easier for the model to generate and less sensitive to vocab if we made the output more natural.
> 
> ```
> Prompt + X
> 
> What chain of relations between topic entity and answer could be used to solve the following question:
> 
> The final of which sport at the 1900 Olympics in Paris attracted 6,000 spectators, the largest crowd at any event at that Olympics?
> 
> Y
> 
> olympics, olympic games, sports
> ```

That makes sense to me. Originally, I kept the "." notation because I thought a more natural output might lose the structural/compositional aspect of the inference chain, but in hindsight that seems like a less relevant concern. Do you think   something like `olympics, olympic games, sports` is preferable to `olympics to olympic games to sports`?

**Comment by stephenbach** [comment]
Great! Nope, no preference between the two. Up to you!

**Comment by rteehas** [comment]
I ended up sticking with the ", " format. I thought "to" would imply causality or direction when it's not strictly true that that's the case

**Comment by srush** [comment]
These chain of inference prompts seem basically impossible to know without the dataset. I think we should just remove them?

**Comment by rteehas** [comment]
> These chain of inference prompts seem basically impossible to know without the dataset. I think we should just remove them?

I mainly included them based on a comment in the Freebase paper about training to search through the database. I thought that that could be a proxy for learning a set of inference steps. One thing I could do that might make more sense, if you think that's less useful, is exclude everything but the first and last link in the chain and rephrase the prompt to ask what kinds of objects the question is connecting (i.e. what kind of object is the question about and what kind of object do you expect the answer to be).

**Comment by stephenbach** [comment]
Yeah, agree with @srush here. Was on the fence, but not clear that there’s a generalizable skill here. Fine to just cut them and have the QA templates.

**Comment by rteehas** [comment]
Ok, in that case I'll add some more QA style templates to make up for the removed inference chain ones

**Comment by rteehas** [comment]
Do you think it wouldn't be useful to have a task where the goal is to identify the category the answer is in?

**Comment by stephenbach** [comment]
Yup, I think that makes more sense.

**Comment by stephenbach** [comment]
Thank you!

**Pull request merged**
