### PR TITLE
prompt kilt/hotpotqa

### PR DESCRIPTION
**Pull request by VictorSanh**
cc @awebson

### CODE REVIEW

**Comment by awebson** [comment]
As we cast Hotpot as a closed-book QA, the questions are neither "complex" nor "elaborate" as some of the prompts here describe. I don't know @craffel if you think it's still worth rewriting them now?

**Comment by craffel** [comment]
> As we cast Hotpot as a closed-book QA, the questions are neither "complex" nor "elaborate" as some of the prompts here describe. I don't know @craffel if you think it's still worth rewriting them now?

Eh I think it's fine to describe them in this way, since they do require multi-step reasoning even if the context isn't given. And after all, didn't we decide that "human"-y prompting was not the most pertinent bit here? But, yes, we also could just have a prompt that is literally {{question}} ||| {{answer}} or some such thing.

**Comment by awebson** [comment]
I guess to what extent do we want to enforce humanly/semantically plausible prompt is a separate debate that we can't resolve now. I don't have strong feelings in this particular case though, so feel free to merge unless you find other bugs in these templates.

**Comment by craffel** [comment]
Yes, I guess I am saying: these are reasonably humanly/semantically plausible!

**Comment by craffel** [comment]
The only other prompts I would add would be something like
```
FINAL EXAM

Question 1. {{question}}
|||
{{answer}}
```
or silly things like that. Otherwise LGTM.

**Pull request merged**
