### PR TITLE
added scan dataset

### PR DESCRIPTION
**Pull request by teelinsan**
Hi all, added prompts for the [SCAN](https://github.com/brendenlake/SCAN) dataset.

### CODE REVIEW

**Review by VictorSanh — CHANGES_REQUESTED** [review]
Thank you @teelinsan , SCAN is a fun one!

A few comments:
- Can you indicate the `task_template` flag in the yaml file? I believe it should be all the templates that are not "reversed" (I.e. taking the natural language and predict the instructions)
- It's not realistic to expect the model to know things like "SCAN" or the commands. For all templates, please include a description like `the possible actions are: I_TURN_RIGHT: turn right, I_WALK: walk straight, etc.`, and copy-paste it for all templates (not necessarily at the same position depending on the template) + protect the commands: `{{"I_TURN_RIGHT"}}`

**Comment by teelinsan** [comment]
Hi @VictorSanh 

- Thanks, I've accidentally missed the task_template flag (now fixed). I also decided to remove the "reversed scan" templates since I realized that the reversed task wasn't well defined (e.g., I_TURN_RIGHT I_TURN_RIGHT could have been both "turn opposite right" and "turn right twice")
- If the model is trained on the training dataset of SCAN, I think it can be realistic to ask the SCAN actions without giving the explicit mapping to the model. At the end we are asking the model to translate the commands in natural language to the specific SCAN actions and, like in Machine Translation, we don't give a word-to-word mapping. However I think that an explicit mapping can be useful and might be interesting to do comparison experiments, so I added other prompt templates that include this explicit mapping and kept also the previous templates without mapping.

**Review by VictorSanh — APPROVED** [review]
thank you, merging now, please update the spreadsheet!

**Comment by VictorSanh** [comment]
> * If the model is trained on the training dataset of SCAN, I think it can be realistic to ask the SCAN actions without giving the explicit mapping to the model. At the end we are asking the model to translate the commands in natural language to the specific SCAN actions and, like in Machine Translation, we don't give a word-to-word mapping. However I think that an explicit mapping can be useful and might be interesting to do comparison experiments, so I added other prompt templates that include this explicit mapping and kept also the previous templates without mapping.

Thank you!
Yes I agree. My rationale is that you want the model to reason over the inputs and not necessarily learn the specifics of the dataset (i.e. the mapping between individual command and what they mean). Ultimlately, these commands could be something like `command 3`, `command 5`, `command 78`, and it wouldn't change the task that much (it turns out that the command codes are in semi-formal language).

**Pull request merged**
