### PR TITLE
Add templates for xquad_r dataset (English)

### PR DESCRIPTION
**Pull request by satvikipathak**

### CODE REVIEW

**Review by srush — CHANGES_REQUESTED** [review]
We decided not to make the system produce index numbers like (start position). We're going to keep it to textual output.

**Comment by srush** [comment]
Ping @satvikipathak

**Comment by satvikipathak** [comment]
Hi @srush, I've made the requested changes. Apologies for the delay. Not sure why some checks are failing. Can you please advise?

**Comment by srush** [comment]
It's not your fault they are failing. I will look into why.

**Review by srush — APPROVED** [review]

**Pull request merged**
