### PR TITLE
Coqa quac expanded

### PR DESCRIPTION
**Pull request by stephenbach**

### CODE REVIEW

**Comment by craffel** [comment]
Looks like the tests don't like the Hub dataset - I assume this is because they'd have to download and prepare locally first?

**Comment by stephenbach** [comment]
Yes, that's right. Will revisit how to organize this more nicely after the deadline.

**Comment by craffel** [comment]
This looks good, we might also want a GPT-3 style one with no "prompt" other than the Q: at the end.

**Comment by craffel** [comment]
(but feel free to merge)

**Pull request merged**
