### PR TITLE
Removed IMDB template with negated labels

### PR DESCRIPTION
**Pull request by Urmish**

### CODE REVIEW

**Review by awebson — APPROVED** [review]

**Review by awebson — CHANGES_REQUESTED** [review]
Thank you for cleaning these templates! They look good, except could you please restore the negation template with cleaned metadata? Sorry we weren't clear about this.

**Comment by Urmish** [comment]
Sure. But just to confirm, 4b of this document - https://docs.google.com/document/d/1oPkgh4wqPa2MGhkIfYzJapxeDNh34A__Hq_8u8WcJXI/edit#heading=h.svf8pfawpg8z

Says that "Negated answers: For example, “which of the following is not a correct answer?” “Does the premise contradict the hypothesis?” Negations remain elusive for LMs in general, we should either exclude these prompts or systematically include negated versions of all prompts in train/eval."

The excel sheet - https://docs.google.com/spreadsheets/d/10SBt96nXutB49H52PV2Lvne7F1NvVr_WZLXD8_Z0JMw/edit#gid=1366407787
also mentioned "negated answers" as issues in "Existing issues" column. 

So I am a bit confused about this. What is expected in the end?

**Comment by Urmish** [comment]
@awebson - Added back the negation template

**Review by awebson — APPROVED** [review]
Thank you!

**Pull request merged**
