### PR TITLE
Clean coqa

### PR DESCRIPTION
**Pull request by nihalnayak**
This PR cleans COQA prompts. Added additional prompts to ensure there are five original task prompts.

### CODE REVIEW

**Comment by VictorSanh** [comment]
looking into this now

**Comment by VictorSanh** [comment]
ok, i think it was something with the download (server wasn't responsive during the whole download...), I just relaunched the test and it worked

**Comment by nihalnayak** [comment]
@VictorSanh I think if the templates look okay, then the PR can be merged.

**Comment by VictorSanh** [comment]
should we look into this again? seems like a duplicate

**Pull request closed without merging**
