### PR TITLE
Add Quora Duplicate Question Classification Dataset

### PR DESCRIPTION
**Pull request by blackrosedragon2**
I am a little unsure on if the `quora_localization_1` is correct or not. Do let me know if there are any other things I need to fix!

### CODE REVIEW

**Review by stephenbach — CHANGES_REQUESTED** [review]
Thanks! These are nice! I would just take out quora_basic_1 and quora_localization_1. quora_basic_1 conflicts with quora_basic_2 because they have the same input but different outputs (and I think yes/no is a more natural answer).

And I would take out quora_localization_1 because I don't think there's enough context for the model to understand what it is you want it to do. Perhaps you could change it to a paraphrasing task for the ones that are duplicates? (Just output nothing for examples that are not duplicates.)

Also any template that does duplicate detection should be marked as a task template.

Thank you!

**Comment by blackrosedragon2** [comment]
> Thanks! These are nice! I would just take out quora_basic_1 and quora_localization_1. quora_basic_1 conflicts with quora_basic_2 because they have the same input but different outputs (and I think yes/no is a more natural answer).
> 
> And I would take out quora_localization_1 because I don't think there's enough context for the model to understand what it is you want it to do. Perhaps you could change it to a paraphrasing task for the ones that are duplicates? (Just output nothing for examples that are not duplicates.)
> 
> Also any template that does duplicate detection should be marked as a task template.
> 
> Thank you!

On it !

**Comment by stephenbach** [comment]
Looks great! Would you just check the task template box for the other templates that do duplicate detection as well? Thank you!

**Comment by stephenbach** [comment]
Sorry to drag this out, I think all the duplicate detection ones should be marked true? Only the paraphrasing one seems different from the original task?

**Comment by blackrosedragon2** [comment]
> Sorry to drag this out, I think all the duplicate detection ones should be marked true? Only the paraphrasing one seems different from the original task?

I'm sorry, I think I misunderstood the checkbox button! I will make the fix now.

**Comment by stephenbach** [comment]
Awesome, thank you!

**Pull request merged**
