### PR TITLE
Clean evidence infer treatment.

### PR DESCRIPTION
**Pull request by stephenbach**

### CODE REVIEW

**Comment by stephenbach** [comment]
Download of subset 2.0 seems to be failing. Not sure why since I can download locally. Here's the backtrace:
```
Traceback (most recent call last):
  File "test/show_templates.py", line 25, in <module>
    dataset = get_dataset(dataset_name, subset_name)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/promptsource/utils.py", line 49, in get_dataset
    builder_instance.download_and_prepare()
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datasets/builder.py", line 596, in download_and_prepare
    dl_manager=dl_manager, verify_infos=verify_infos, **download_and_prepare_kwargs
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datasets/builder.py", line 666, in _download_and_prepare
    self.info.download_checksums, dl_manager.get_recorded_sizes_checksums(), "dataset source files"
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datasets/utils/info_utils.py", line 33, in verify_checksums
    raise ExpectedMoreDownloadedFiles(str(set(expected_checksums) - set(recorded_checksums)))
datasets.utils.info_utils.ExpectedMoreDownloadedFiles: {'http://evidence-inference.ebm-nlp.com/v2.0.tar.gz'}
```

**Comment by VictorSanh** [comment]
i am running into the same error, i opened [an issue](https://github.com/huggingface/datasets/issues/3515)

**Comment by VictorSanh** [comment]
Could be worht it to revisit since the bug has been fixed on datasets' master

**Comment by stephenbach** [comment]
I can't seem to re-run the tests that are so old, so I will push a minor change and revert it to get the tests to run again.

**Comment by stephenbach** [comment]
Got the same error
```
Traceback (most recent call last):
  File "test/show_templates.py", line 25, in <module>
    dataset = get_dataset(dataset_name, subset_name)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/promptsource/utils.py", line 51, in get_dataset
    builder_instance.download_and_prepare()
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datasets/builder.py", line 595, in download_and_prepare
    dl_manager=dl_manager, verify_infos=verify_infos, **download_and_prepare_kwargs
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datasets/builder.py", line 666, in _download_and_prepare
    self.info.download_checksums, dl_manager.get_recorded_sizes_checksums(), "dataset source files"
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datasets/utils/info_utils.py", line 33, in verify_checksums
    raise ExpectedMoreDownloadedFiles(str(set(expected_checksums) - set(recorded_checksums)))
datasets.utils.info_utils.ExpectedMoreDownloadedFiles: {'http://evidence-inference.ebm-nlp.com/v2.0.tar.gz'}
```
Maybe we need to wait for a new datasets release?

**Comment by VictorSanh** [comment]
oh yeah, you need to be on the master branch of datasets. the CI tests will fail on Github but if you they pass locally, that will be fine!

**Comment by stephenbach** [comment]
Ok, double checked that the failing tests pass locally. Merging now.

**Pull request merged**
