### PR TITLE
Fix detection of fixed answer choices.

### PR DESCRIPTION
**Pull request by stephenbach**
Now a "fixed" set of answer choices is defined as an answer choices expression that doesn't use any variables.

### CODE REVIEW

**Comment by craffel** [comment]
We might want to test this by instantiating the datasets that eventually produced -1 and confirming that the examples are no longer -1.

**Comment by stephenbach** [comment]
I’ve confirmed that the function returns the right results on some different templates. I think to test further, @VictorSanh could you recache and check?

**Comment by craffel** [comment]
No need to recache! Postprocessing is not cached.

**Comment by craffel** [comment]
Looks like this works.

Without this fix: https://colab.research.google.com/drive/1ZvleQkCbAvErJ-U3jAQh-JuXZ3pQ1lwf?usp=sharing

With this fix: https://colab.research.google.com/drive/1ULEQz2wh5welxrLZoZ78iqDr6aMh_mPe?usp=sharing

Merging.

**Pull request merged**
