### PR TITLE
Add metrics to the docred dataset

### PR DESCRIPTION
**Pull request by tae898**
I used the below three rules to add metrics:

1. If specific words have to be in the answer, the metric is accuracy.
2. If a text has to be generated in the answer, the metrics are BLEU and ROUGE.

~~3. If both 1 and 2 have to be satisfied, the metrics are accuracy, BLEU, and ROUGE.~~

### CODE REVIEW

**Review by stephenbach — CHANGES_REQUESTED** [review]
Great! A few thoughts:
- Let's change the metrics to Other, because it requires parsing the output and counting individual matches. Accuracy should only be used when counting exact matches to the target.
- There's a bug in rendering at least some of the prompts, where the last token of a sentence (usually a period) doesn't have a space before the first token of the next sentence.
- In the "find all numbers" prompt, I would clarify that it's asking just for numbers expressed in words (not numerals).
- For ner-type, please take out the example (remember to ask for its label instead), so that it remains zero-shot. There's also a lot of blank lines. (Maybe a big code block?)
- Also for ner-type, answer choices should not be set, because that's not the list of all possible outputs.
- relation is also not zero shot.

**Comment by stephenbach** [comment]
Thanks! I think the whitespace thing is important to fix because it affects tokenization. Perhaps there's a way to concatenate all the sentences together before joining. At the very least, you could just put a space each sentence in the for loop I think?

**Comment by stephenbach** [comment]
Sorry, I missed your question about the numbers. It looked to me like it doesn't include numerals?

**Comment by tae898** [comment]
> Thanks! I think the whitespace thing is important to fix because it affects tokenization. Perhaps there's a way to concatenate all the sentences together before joining. At the very least, you could just put a space each sentence in the for loop I think?

Alright I added a white space between setnences.

**Comment by tae898** [comment]
> Sorry, I missed your question about the numbers. It looked to me like it doesn't include numerals?

There are some:
image

image

**Review by stephenbach — APPROVED** [review]
Looks great! Thanks! I think I was seeing days and years, which aren't tagged. Thanks for checking.

**Pull request merged**
