### PR TITLE
Discovery

### PR DESCRIPTION
**Pull request by arunraja-hub**

### CODE REVIEW

**Review by stephenbach — CHANGES_REQUESTED** [review]
Thank you! For the label names like `in_sum`, would you please rewrite them to be English words (no underscores)?

**Comment by arunraja-hub** [comment]
Thank you, I have removed the underscores

**Comment by stephenbach** [comment]
Thanks, would you also change the `[no-conn]` label to something more natural like `No connection` or `None`? In general, the prompts and outputs should be natural language that complements the text that's collect "from the wild."

**Review by stephenbach — APPROVED** [review]
LGTM, thanks! Please mark as completed on spreadsheet.

**Pull request merged**
