### PR TITLE
Add template for Mocha dataset

### PR DESCRIPTION
**Pull request by yongzx**
Notes:
1. The dataset has a "minimal_pairs" split that has two candidate answers instead of one (as in the "train", "validation", "test" split). I have include if-else blocks to handle them. 
2. For the `Pick Correct Answer` template, to prevent the reference answer from always showing up as the first answer, I use the following hack: use the length of the passage to determine if we should right shift the list of answers (that includes reference and candidates). If so, perform the right shift before listing the answers out.

### CODE REVIEW

**Comment by craffel** [comment]
It seems for the "scoring candidate" variants, the model could judge equivalency of answers without access to the context and question. If that's the case, do you want to include variants of the task where the model is just rating/classifying similarity of the answers? You could also do it with only the question and answer, and not the context sentence. WDYT?

**Comment by yongzx** [comment]
> If that's the case, do you want to include variants of the task where the model is just rating/classifying similarity of the answers? You could also do it with only the question and answer, and not the context sentence.

I could definitely include these two variants!

**Comment by yongzx** [comment]
@craffel Added the variants for both regression and classification tasks.

**Comment by craffel** [comment]
Thanks!

**Pull request merged**
