### PR TITLE
Some tweaks to the Editor

### PR DESCRIPTION
**Pull request by srush**
* Default sort by popularity and include number of prompts 

image

* Global progress table 

image

* Separated out new prompts and select, and the columns (I think this is okay, but might break)

image

* Added text wrapping so that you can view long prompts

* Added a template viewer section 

image

### CODE REVIEW

**Comment by stephenbach** [comment]
Awesome! I love it!

I'm having some rendering issues for TREC in the template viewer:
screenshot
I can look more into, but just flagging in case you know a quick fix.

More broadly, @VictorSanh added some template viewing capabilities to promptapp.py. Do we want to merge them together in this PR?

**Comment by VictorSanh** [comment]
Also, for the template viewer, I think it's more important to be able to scroll through a lot of examples for a given prompt than scrolling through a lot of prompts for a given example to quickly identify potential bugs (see example #36), thus my comment on overlapping global viewers

**Comment by srush** [comment]
@VictorSanh I think the reason I liked the viewer in this tool as well, was just to make sure that people don't overwrite the same prompt many times. Makes it easy to see what is there when adding a new prompt.

**Comment by srush** [comment]
@stephenbach here is what my side looks like. 

image

Wonder if it is a wide / narrow screen thing.

**Comment by VictorSanh** [comment]
> @VictorSanh I think the reason I liked the viewer in this tool as well, was just to make sure that people don't overwrite the same prompt many times. Makes it easy to see what is there when adding a new prompt.

Right, during the sprint we won't have such a problem because one dataset = one person, so you won't have multiple people working on the same dataset at the same time (and thus the coordination through the spreadsheet)

**Comment by stephenbach** [comment]
@srush Does fine_grained_context_first render correctly as well? The first one looks same for me as your screenshot.

And yeah, +1, definitely a good motivating case for filters.

**Comment by shanyas10** [comment]
A bug I found (essentially a streamlit issue) was that the selected dataset (in the dropbox) changes as soon as we add a new template. This is because the rendered string in the dropdown changes ( count in parans increase by 1) and streamlit has some issues rendering such dynamic data (similar to [this](https://github.com/streamlit/streamlit/issues/1259)). I was also not able to find any workaround to fix this.  

(Apologies if this has already been reported)

**Comment by srush** [comment]
@stephenbach fixed the formatting
image

@shanyas10 oh you are right! bummer. turned that off.

**Comment by VictorSanh** [comment]
@srush as discussed yesterday can you remove the "Template Viewer Section" as it duplicated from the Prompted dataset viwer?
I'll merge this pull requests then! 

(I'll work on merging the 3 modes - sourcing, helicopter view, prompted dataset viewer - into a single app)

**Comment by srush** [comment]
@VictorSanh fixed.

**Comment by VictorSanh** [comment]
awesome, thank you, merging it!

**Pull request merged**
