### PR TITLE
Add uuid to each template | allow for name updates

### PR DESCRIPTION
**Pull request by arnaudstiegler**
This PR introduces:
- a unique identifier for each template entry
- we can now update the name of a template without having to create a new entry in the yaml file
- reformatted the current yaml files to have the newly added ids. Nothing has been changed in the names/templates/references

Even if we use uuids as keys for the templates, we still use the names to index them in the UI. So there's a mapping between name and ids to allow to pass a name to update a template, and there's a sync function that ensures any updates in self.templates is applied to the mapping as well

NB: all git diffs for the templates are solely due to some re-ordering based on the new ids

### CODE REVIEW

**Comment by arnaudstiegler** [comment]
#29

**Comment by stephenbach** [comment]
Thank you! I submitted some templates for TREC right before you submitted this one. Would you mind pulling and updating the format for those too to make sure they're correct?

**Comment by stephenbach** [comment]
I think there's still an issue (unrelated to trec). When I merge this PR into main locally I get the following error on the app:
```
AttributeError: 'Template' object has no attribute 'id'
Traceback:
File "/Users/bach/anaconda3/envs/bigscience/lib/python3.7/site-packages/streamlit/script_runner.py", line 338, in _run_script
    exec(code, module.__dict__)
File "/Users/bach/promptsource/promptsource/promptsource.py", line 84, in <module>
    template_collection = TemplateCollection()
File "promptsource/templates.py", line 27, in __init__
    self.datasets_templates: Dict[(str, Optional[str]), DatasetTemplates] = self._collect_dataset()
File "promptsource/templates.py", line 49, in _collect_dataset
    output[(dataset, filename)] = DatasetTemplates(dataset_name=dataset, subset_name=filename)
File "promptsource/templates.py", line 100, in __init__
    self.sync_mapping()
File "promptsource/templates.py", line 106, in sync_mapping
    self.name_to_id_mapping = {template.name: template.id for template in self.templates.values()}
File "promptsource/templates.py", line 106, in <dictcomp>
    self.name_to_id_mapping = {template.name: template.id for template in self.templates.values()}
```
It looks like your branch is behind main. Would you first pull main into your branch, test, and let us know when it's ready? Thank you!

**Comment by arnaudstiegler** [comment]
Indeed, I was missing the winogrande folder in my branch which had a template.yaml with the old format (i.e no template.id).
Merged main into my branch, tested locally, all seems to work.

As an aside, the sorting of the templates within the `templates.yaml` is now based on the random uuid unfortunately... So when you add a new template, it's randomly inserted in the file. I don't see an easy fix for that for now, so I'm returning the sorted list of template names so that at least in the UI, the templates are sorted alphabetically.

**Comment by stephenbach** [comment]
Beautiful!! Sorry to add more for you to do, but @VictorSanh just fixed the code quality checks. Would you pull main one more time, run `make quality` and `make style` and then do one more commit? Thank you!

**Comment by arnaudstiegler** [comment]
Done!

**Comment by stephenbach** [comment]
Awesome, thank you!

**Pull request merged**
