### PR TITLE
Clean freebase_qa, craigslist_bargains, health_fact, hyperpartisan_news_detection

### PR DESCRIPTION
**Pull request by jason-fries**
For this task I:
- Added accuracy metrics to all prompts
- Assigned "original task" to the minimal QA prompt template (vs. the ones that add additional contextual information) 
Each template makes some style changes (e.g., capitalizing answers in-prompt) that I don't if we should leave as-is or remove for simpler templates.

### CODE REVIEW

**Comment by stephenbach** [comment]
Thanks! Let's make them all original task. It's more about the broad skill that's required than exactly what info is provided. Prompts that have additional context should still be considered original task.

**Comment by jason-fries** [comment]
Updated all the prompts that reflect the original task.

**Comment by jason-fries** [comment]
This PR now contains cleaned up prompts for:
- freebase_qa
- craigslist_bargins
- health_fact
- hyperpartisan_news_detection (byarticle)
- hyperpartisan_news_detection (bypublisher)

**Review by stephenbach — APPROVED** [review]
Thank you!

**Pull request merged**
