### PR TITLE
Spanish prompts for bias-shades

### PR DESCRIPTION
**Pull request by ArjunSubramonian**

### CODE REVIEW

**Comment by stephenbach** [comment]
Thanks! I had enough spanish in school that these I can sort of understand, but the same feedback as #761 seems to apply here as well. Also it looks like the answer choices won't render correctly because they're separated with `||` instead of `|||`.

**Review by jzf2101 — APPROVED** [review]

**Comment by oskarvanderwal** [comment]
@ArjunSubramonian, apparently, the prompt [convert_to_stereotype](https://github.com/bigscience-workshop/promptsource/blob/e3a22e09d0131a6ca6810ad8684c59eab3ede13d/promptsource/templates/BigScienceBiasEval/bias-shades/spanish/templates.yaml#L48) is raising some issues in [lm-eval-harness](https://github.com/bigscience-workshop/lm-evaluation-harness/pull/37#pullrequestreview-1171340441).  Can we remove prompt 3aaea02b-becc-4eef-94e3-059e5146c801?

**Comment by ArjunSubramonian** [comment]
> @ArjunSubramonian, apparently, the prompt [convert_to_stereotype](https://github.com/bigscience-workshop/promptsource/blob/e3a22e09d0131a6ca6810ad8684c59eab3ede13d/promptsource/templates/BigScienceBiasEval/bias-shades/spanish/templates.yaml#L48) is raising some issues in [lm-eval-harness](https://github.com/bigscience-workshop/lm-evaluation-harness/pull/37#pullrequestreview-1171340441). Could you have a look at it?

I took a look and don't know what the issue is :( Does the prompt also cause an issue for Hindi? https://github.com/bigscience-workshop/promptsource/pull/761/files. The Hindi and Spanish prompts appear identical to me.

**Comment by jon-tow** [comment]
Hi, @ArjunSubramonian ! The Hindi version of the prompt also results in that same error. I'll merge the PR on the eval-harness side so that we can await the `promptsource` fix asynchronously (I don't want to hold back y'all's rush for such a minor issue).

**Pull request merged**
