### PR TITLE
Templates for `ncbi_disease`

### PR DESCRIPTION
**Pull request by drugilsberg**
This one compared to the others has been a real pain, but I think the templates are quite interesting.
Not sure the Jinja style is top notch, but it seems functional on the example sets I checked.

### CODE REVIEW

**Comment by drugilsberg** [comment]
Not sure what the check is detecting here: https://github.com/bigscience-workshop/promptsource/runs/2795972372?check_suite_focus=true.
Anyone who can help?

**Comment by drugilsberg** [comment]
@stephenbach sorry to tag you, but I noticed you are one of the gurus on slack ;)

**Comment by drugilsberg** [comment]
> @stephenbach sorry to tag you, but I noticed you are one of the gurus on slack ;)

Not sure what is going on, I followed the usual procedure (did the same for the other two datasets I worked on) :(

**Comment by stephenbach** [comment]
No worries. 😃 The error message is
```
ValueError: Template for dataset ncbi_disease/None with uuid 04458e59-37f1-48dc-bb20-823e836a8c44 has unrecognized variable disease_token.
```
But not sure why it's unrecognized since you're setting it. Does it render ok in the app?

**Comment by drugilsberg** [comment]
See here for example, the variable is set and used, and rendered properly. Same applies when I inspect the examples outside of the `Sourcing` view. Could it be that test is overlooking the `set` directive?

image

**Comment by stephenbach** [comment]
Hmm, not sure. We use Jinja itself to decide which variables are unset. Will have to look more into this and get back to you.

**Comment by stephenbach** [comment]
Per slack discussion, seems the issue is that the variable `disease_token` is only set inside an if statement. If you also set a default value for the if statement, it should pass the test. A little hacky, but easier than messing around with Jinja internals.

**Comment by drugilsberg** [comment]
@stephenbach ready for review, I also made sure that the task template flag is present in all the templates.

**Comment by stephenbach** [comment]
Great, thank you!

**Pull request merged**
