### PR TITLE
Added species_800

### PR DESCRIPTION
**Pull request by teelinsan**
Added the dataset species_800. Thanks to @drugilsberg for the jinja NER processing pipeline.

### CODE REVIEW

**Review by VictorSanh — CHANGES_REQUESTED** [review]
This one looks like a complicated one!

One remark: can you describe in a few words what the NCBI Taxonomy is? something like (`NCBI Taxonomy (species of organism that have this particular attribute)`.

Otherwise, let's replace all occurrences of `NCBI Taxonomy` with `species or organisms` or something shorter. My rule of thumb is: if as a human I saw this text, would I be able to complete the task correctly?

**Comment by teelinsan** [comment]
Thanks @VictorSanh 
Added a short example and clarification of what is a species of the NCBI Taxonomy + minor fixes.

**Comment by teelinsan** [comment]
The `show_new_templates` check seems to fail since it is unable to download the dataset. However, using the same link I can download it.

`ConnectionError: Couldn't reach https://drive.google.com/u/0/uc?id=1OletxmPYNkz2ltOr9pyT0b0iBtUWxslh&export=download/
Error: Process completed with exit code 1.`

**Comment by VictorSanh** [comment]
> The `show_new_templates` check seems to fail since it is unable to download the dataset. However, using the same link I can download it.
> 
> `ConnectionError: Couldn't reach https://drive.google.com/u/0/uc?id=1OletxmPYNkz2ltOr9pyT0b0iBtUWxslh&export=download/ Error: Process completed with exit code 1.`
> 
> Might be a timeout issue.

Yes don't worry, merging now, please update the spreadsheet!

**Pull request merged**
