### PR TITLE
Craigslist bargains prompts

### PR DESCRIPTION
**Pull request by relaxedplan**
Added prompts covering the following tasks related to craigslist_bargains:
 - generating the next line of negotiation from a specified intention (main task)
 - determining if the buyer or the seller got the best deal
 - determining the gap between the buyer's target and the seller's target

### CODE REVIEW

**Review by srush — CHANGES_REQUESTED** [review]
It seems like the for loop here is failing on some examples in the test.

**Comment by relaxedplan** [comment]
> It seems like the for loop here is failing on some examples in the test.

You're right, it was failing when the only items in "Price" were -1. Should be fixed now :)

**Comment by srush** [comment]
Looks like it is still failing :)

**Comment by relaxedplan** [comment]
seems like it passes now :)

**Pull request merged**
