### PR TITLE
Add metrics to the turk dataset

### PR DESCRIPTION
**Pull request by tae898**
I used the below three rules to add metrics:

1. If specific words have to be in the answer, the metric is accuracy.
2. If a text has to be generated in the answer, the metrics are BLEU and ROUGE.

~~3. If both 1 and 2 have to be satisfied, the metrics are accuracy, BLEU, and ROUGE.~~

### CODE REVIEW

**Comment by tae898** [comment]
> Thanks! Minor thing: are none of these original tasks?

Now, I marked the simplification tasks as original tasks.

> More major thing: a lot of the simplifications are duplicates of the original, resulting in prompts like this: image Is there a way to filter out duplicates, and return a prompt from the remaining ones (if any are left)?

Yeah unfortunately the data is not so clean. Among the eight possible simplified answers, the target is chosen randomly with the below code:

```jinja
{{simplifications | choice}}
```

I don't think there is a way to select only simplified texts...

**Comment by stephenbach** [comment]
It's not pretty, but you can get such a list called `real_simplifications` by inserting this code at the top of the template:
```jinja2
{% set real_simplifications = [] %}{% for text in simplifications %}{% if text != original %}{% set tmp = real_simplifications.append(text) %}{% endif %}{% endfor %}
```
Keep it all on one line to avoid inserting a bunch of new lines.

**Comment by tae898** [comment]
> It's not pretty, but you can get such a list called `real_simplifications` by inserting this code at the top of the template:
> 
> ```
> {% set real_simplifications = [] %}{% for text in simplifications %}{% if text != original %}{% set tmp = real_simplifications.append(text) %}{% endif %}{% endfor %}
> ```
> 
> Keep it all on one line to avoid inserting a bunch of new lines.

That's a very good suggestion. Your suggestion only works when there is an exact string match, which doesn't look like it happens often. So I made a modification to it:

```jinja
{% set real_simplifications = [] %}{% for text in simplifications %}{% if text|length < original|length %}{% set tmp = real_simplifications.append(text) %}{% endif %}{% endfor %}
``` 

I kinda like this solution. If you also like it, I can add this in the `CONTRIBUTING.md` as well.

**Comment by tae898** [comment]
I had to add a small trick to get it working:

```jinja
{% set real_simplifications = [] %}{% for text in simplifications %}{% if text|length < original|length %}{{real_simplifications.append(text) | default("", True)}}{% endif %}{% endfor %}
```

**Comment by stephenbach** [comment]
Great! I think we still need to wrap the templates in an if statement to check if the len of real_simplifications in non-zero?

**Comment by tae898** [comment]
> Great! I think we still need to wrap the templates in an if statement to check if the len of real_simplifications is non-zero?

That's a good point. Although I haven't seen such a case, it'd be to safe to add such a thing. 

I can't really code until Monday (CET timezone). If you want to merge this fast, you can add the if statement and merge the PR.

**Comment by stephenbach** [comment]
No rush! Sorry, I'm swamped too. :) We could also just run a quick check and see if any are actually zero. If not, should be fine.

**Comment by tae898** [comment]
@stephenbach done!

**Comment by stephenbach** [comment]
Looks great! I verified that it outputs a blank result when there are no real simplifications. Thanks!

**Pull request merged**
