### PR TITLE
Asset simplification

### PR DESCRIPTION
**Pull request by tae898**
* Added two more prompt templates.
* Specified metrics and answer choices, if possible.
* Added a sanity check to ensure that simplified sentence is actually shorter than the original.

The sanity check trick was developed [here](https://github.com/bigscience-workshop/promptsource/pull/570).

### CODE REVIEW

**Comment by VictorSanh** [comment]
I opened a PR @tae898 to fix the data download
  https://github.com/huggingface/datasets/pull/3516
  Using this PR, you should be able to do both subsets (`simplification` and `ratings`)

**Comment by tae898** [comment]
@stephenbach 

You want to do the `ratings`, right?

**Comment by stephenbach** [comment]
I was taking it out of necessity, so if you can download it and have the time, it’d be great if you could do it! Thanks!

**Comment by tae898** [comment]
haha alright sure, I'll take care of it :)

**Comment by VictorSanh** [comment]
thanks for working on @tae898 
i pushed a small fix
merging now

**Pull request merged**
