### PR TITLE
Clean copa.

### PR DESCRIPTION
**Pull request by stephenbach**

### CODE REVIEW

**Review by craffel — COMMENTED** [review]
Shouldn't this have `answer_choices: [choice1, choice2]` on all the templates?

**Review by craffel — COMMENTED** [review]
Some of the prompts here will discard part of the dataset (for example, all of the examples where question is not "cause" could be discarded if the prompt wraps things in a conditional like `{% if question == "effect" %}`. I think this means they aren't an "original task" prompt. We could probably merge the complementary prompts together so that all examples pass through. WDYT?

**Comment by stephenbach** [comment]
I think we might have consensus in the slack thread that original_task should remain about skills and not differentiate between such variants?

Either way, pushed some changes that updates the `answer_choices_key` format if you wouldn't mind double checking that too.

**Comment by craffel** [comment]
My concern is not whether it's the original task or not, but that if we eval on these prompts we will not be getting numbers over the full dataset, which I think we should avoid. So I think we should probably avoid prompts that avoid a conditional that discards examples, if it's a task we're going to eval on.

**Review by craffel — APPROVED** [review]

**Pull request merged**
