### PR TITLE
Add prompts for BioASQ task b

### PR DESCRIPTION
**Pull request by apsdehal**
Following [BLURB](https://microsoft.github.io/BLURB/) benchmark we use
task 7b and only yes/no question in that specifically to be comparable
to other models.

We use prompts similar to BoolQ prompts

Resolves: https://github.com/bigscience-workshop/evaluation/issues/29

### CODE REVIEW

**Comment by awebson** [comment]
Does `aps/bioasq_task_b` require manual download? I'm getting the following error: 

```
Original error: Couldn't find file at https://huggingface.co/datasets/aps/bioasq_task_b/resolve/main/~/.cache/promptsource/aps/bioasq_task_b/bioasq_2b_source/BioASQ-trainingDataset2b.zip
```

**Comment by apsdehal** [comment]
@awebson Yes, it does. Please download from task 7b from http://participants-area.bioasq.org/datasets/ and use subset `bioasq_7b_qa_yes_no_only`

**Comment by awebson** [comment]
Sorry, is the attached screenshot the correct subset I'm supposed to download? Clicking that directs me to a login page.

スクリーンショット 2022-04-27 18 06 23

**Comment by apsdehal** [comment]
Hi, yes that subset is correct and yes you will have to login. It is a gated dataset, unfortunate.

**Comment by apsdehal** [comment]
@awebson Can we finalize this PR? I unfortunately can't share the dataset publicly as that would be violation of agreement for the original dataset.

**Review by awebson — APPROVED** [review]
Thanks for the suggestion of changing the `DEFAULT_PROMPTSOURCE_CACHE_HOME` in `promptsource/__init__.py`. I was finally able to load this dataset. @stephenbach, does it make sense if we change that to the following? 
```
from pathlib import Path
DEFAULT_PROMPTSOURCE_CACHE_HOME = str(Path("~/.cache/promptsource").expanduser())
```

And @apsdehal can you check "allow edits by maintainers" so that I can commit this fix in your branch? Otherwise the prompts look good. However, do note that some of the examples are very long and will likely be truncated, in which case prompts where questions come at the end will also likely be chopped. You can either include these prompts for now and exclude them as needed when you run evaluations later, or you can drop prompts which have questions come at the end. Up to you.

**Comment by apsdehal** [comment]
@awebson I don't see that checkbox anymore but I can make these changes to the PR if that is okay?

**Comment by awebson** [comment]
In the prompt engineering working group meeting today, Stephen mentioned that @VictorSanh was the one who added this `DEFAULT_PROMPTSOURCE_CACHE_HOME`. Victor could you please take a quick look at my suggestion above? If that makes sense to you, then yeah @apsdehal feel free to add it. Thanks!

**Comment by VictorSanh** [comment]
> In the prompt engineering working group meeting today, Stephen mentioned that @VictorSanh was the one who added this `DEFAULT_PROMPTSOURCE_CACHE_HOME`. Victor could you please take a quick look at my suggestion above? If that makes sense to you, then yeah @apsdehal feel free to add it. Thanks!

yes abs! sounds good to me cc @thomasw21 since you first suggested it (we also use a `os.path.expanduser(...)` to handle cache in HF Transformers)

**Comment by thomasw21** [comment]
@awebson sound good!

**Pull request merged**
