### PR TITLE
templates for tweets_hate_speech_detection and hate_speech_offensive

### PR DESCRIPTION
**Pull request by shanyas10**
6 prompts for tweets_hate_speech_detection

### CODE REVIEW

**Comment by shanyas10** [comment]
added prompts for hate_speech_offensive

**Comment by stephenbach** [comment]
These are great, thanks! Love the creativity!

A few minor things related to using more natural/intuitive language:
- Generally hate speech isn't hyphenated.
- For `hate_speech_offensive` can we make it more clear in the question that there's three possible answers: hate speech, offensive, or neither? It wasn't clear to me as a reader.
- In `hate_speech_offensive` / `hate_offense_5` can we make the task more clear, that you're looking for an agreement or disagreement? In the other dataset, the "What do you think?" seemed like a good prompt. I had trouble parsing the negation in it.

**Review by stephenbach — CHANGES_REQUESTED** [review]
Please see comments above. Thanks!

**Comment by shanyas10** [comment]
Hi @stephenbach Thank you for your comments. I'll keep them in mind in the datasets I prompt next. Since we are skipping the datasets with potential harmful content, I'll close this PR.

**Pull request closed without merging**
