### PR TITLE
Clean math_dataset-algebra_linear_1d

### PR DESCRIPTION
**Pull request by Edward-Sun**
This PR cleans the `algebra_linear_1d` subtask from the `math_dataset` dataset. Added more original prompts to the task.

### CODE REVIEW

**Comment by VictorSanh** [comment]
thank you @Edward-Sun , lgtm!
Could you reflect your changes in the other subsets too?
the *_composed have the same format while the non-composed have the same format

**Comment by Edward-Sun** [comment]
Hi Victor, I have applied the same changes to the other three subtasks in math_dataset.

**Comment by VictorSanh** [comment]
Thank you @Edward-Sun !
Merging now, i updated the spreadsheet.
After re-skimming through the paper, I changed the metric to "other" as they use the "probability of correct answer" as the main metric.

**Comment by Edward-Sun** [comment]
Hi @VictorSanh, please correct me if I'm wrong. To my understanding, the **probability of correct answer** mentioned in "Figure 3: **Model accuracy (probability of correct answer)** averaged across modules. " of the paper (i.e., https://arxiv.org/pdf/1904.01557.pdf) just means the accuracy.

**Pull request merged**
