### PR TITLE
dbpedia_14 prompts

### PR DESCRIPTION
**Pull request by Urmish**

### CODE REVIEW

**Review by stephenbach — CHANGES_REQUESTED** [review]
Great, thank you! A couple of changes across the board:

For label names, like Natural Place or Album, please put spaces in them so that they are more natural. Please also don't use articles before the name (see the best practices in the contributing guide).

For places where you have the title and the content separated by a dash or colon, please put spaces around the separator so that it doesn't run together.

Perhaps consider adding at least one that provides choices?

**Comment by Urmish** [comment]
@stephenbach - Thanks for the review! Updated the templates.

**Comment by stephenbach** [comment]
Thanks! A couple more issues: written work is still missing a space in a couple places. For choices that appear in the prompt, they need to be escaped. Please see the contributing guide.

**Comment by Urmish** [comment]
Thanks! I wasn't completely sure about the escaping part, following this format -
image

**Comment by stephenbach** [comment]
Great, thanks! The escaping should be done as one quoted string. Right now it renders as
```E. D. Abbott Ltd -  Abbott of Farnham E D Abbott Limited was a British
coachbuilding business based in Farnham Surrey trading under that name from
1929. A major part of their output was under sub-contract to motor vehicle
manufacturers. Their business closed in 1972. Given a choice of categories
('company', 'educational institution', 'artist', 'athlete', 'office holder',
'mean of transportation', 'building', 'natural place', 'village', 'animal',
'plant', 'album', 'written work'), the text refers to which one?
```
because 
```
 {{"company", "educational      institution", "artist", "athlete", "office holder", "mean of transportation",      "building", "natural place", "village", "animal", "plant", "album", "film" and      "written work"}}
```
turns into a tuple and the "and" gets dropped. So something like
```
 {{"company, educational institution, artist, athlete, office holder, mean of transportation,  building, natural place, village, animal, plant, album, film, or written work"}}
```

**Review by stephenbach — APPROVED** [review]
Awesome, thank you!

**Pull request merged**
