### PR TITLE
Common gen

### PR DESCRIPTION
**Pull request by nihalnayak**
Contains template for common_gen

### CODE REVIEW

**Comment by stephenbach** [comment]
Would you please make this PR just for common gen?

**Comment by nihalnayak** [comment]
@stephenbach made the requested changes.

**Comment by stephenbach** [comment]
Nice! I wonder if we can increase the diversity a bit by replacing some of the similar ones with a template or two that goes the other way: generate concepts from the sentence? Could also use the new choice filter to ask for a single concept.

**Comment by nihalnayak** [comment]
Replaced two previous templates with (1) sentence to concept list (2) choice prompts.

**Comment by stephenbach** [comment]
Awesome, thanks! Can you just mark them all as task template or not? I think the ones where you generate the sentence given all the concepts would be the task templates?

**Comment by nihalnayak** [comment]
Marked all as task templates or not.

**Comment by stephenbach** [comment]
Great, thank you! Please mark the dataset as completed on the spreadsheet.

**Pull request merged**
