### PR TITLE
fix: XSum for ROUGE, `choices_in_prompt`, renaming, and 4 templates

### PR DESCRIPTION
**Pull request by tianjianjiang**

### CODE REVIEW

**Comment by VictorSanh** [comment]
@tianjianjiang please merge your modifications into one PR so we only review it once (cf [my comment](https://github.com/bigscience-workshop/promptsource/pull/361#issuecomment-914568721)). you can import and push commits to the branch you have here

**Comment by tianjianjiang** [comment]
> @tianjianjiang please merge your modifications into one PR so we only review it once (cf [my comment](https://github.com/bigscience-workshop/promptsource/pull/361#issuecomment-914568721)). you can import and push commits to the branch you have here

Understood and done. :)

**Comment by awebson** [comment]
@tianjianjiang Sorry, would you mind deleting the "second grader" template? Few xsum summaries can actually be understood by second graders. It's a relatively large training set and we don't want models to learn a wrong idea of what grade school kids can understand, while there are other datasets do ask for genuine simplifications.

**Comment by tianjianjiang** [comment]
> we don't want models to learn a wrong idea of what grade school kids can understand, while there are other datasets do ask for genuine simplifications.

Sure, I didn't consider this perspective and really appreciate the advice! Related changes are in #404 now.

**Pull request merged**
