### PR TITLE
Add 3 templates for amazon polarity for variety.

### PR DESCRIPTION
**Pull request by Iwontbecreative**
Increases template diversity.

### CODE REVIEW

**Review by VictorSanh — APPROVED** [review]
lgtm

**Comment by VictorSanh** [comment]
waiting for things to settle on the `answer_choices_key` before merging. @awebson do you want to include these templates too in the training?

**Comment by awebson** [comment]
Yup amazon_polarity (seeded from CrossFit) has always been a training set so more templates are good.

**Comment by VictorSanh** [comment]
> Yup amazon_polarity (seeded from CrossFit) has always been a training set so more templates are good.

ok great, i'll let you know when i merge and I'll let you reflect that on your PR to include these new templates into the `d4_train` mixture

**Comment by VictorSanh** [comment]
merging now @awebson

**Pull request merged**
