### PR TITLE
Evidence infer treatment

### PR DESCRIPTION
**Pull request by debajyotidatta**
This dataset is very interesting because the prompts can be varied based on the intervention, comparator, outcome, and the final label of the treatment. Since the number of annotations can vary and the number of sub annotations can also vary, a random subset is selected as the prompt for each example.

### CODE REVIEW

**Review by stephenbach — CHANGES_REQUESTED** [review]
Thank you! These are interesting!

Would you please change these to use the `choice` filter, instead of `random`?

Also, these produce really long prompts that are unlikely to fit in the input to the model. (2048 byte pairs is a reasonable estimate.) We'll try to heuristically trim them, but if there's something smarter that you can do (such as cutting the sections that are least likely to be useful) that would be more likely to produce prompts that preserve your meaning.

**Comment by debajyotidatta** [comment]
@stephenbach: After going through multiple examples, I think the heuristic of using the first 1500 characters of the text and the last 300 characters should provide all the information for making inferences about the data. These sections generally contain the abstract, introduction, key findings, and conclusion.

**Comment by stephenbach** [comment]
Wonderful thanks! Would you also just replace the `|random` filters with `|choice`? Then we should be good to go.

**Comment by debajyotidatta** [comment]
@stephenbach : Replaced random with choice. Sorry about that.

**Comment by stephenbach** [comment]
Great, thank you!

**Pull request merged**
