### PR TITLE
clean_banking77

### PR DESCRIPTION
**Pull request by shanyas10**
Declared the intents as the answer_choices for each template. Is there a way to declare them once, globally?

### CODE REVIEW

**Comment by stephenbach** [comment]
Unfortunately no way to declare them globally since not all prompts share the same answer choices. Also, these need to be expressed more as natural language. (The labels are not words because of the underscores.) See #637 for a similar dataset.

**Comment by shanyas10** [comment]
> Unfortunately no way to declare them globally since not all prompts share the same answer choices. Also, these need to be expressed more as natural language. (The labels are not words because of the underscores.) See #637 for a similar dataset.

I've replace underscores with spaces wherever they're used in prompt or target text. Will that not work? I can change the choices themselves if that's the case.

**Comment by stephenbach** [comment]
Same thing as in #637. Changing the choices in the target creates a bug. The choices always need to match the targets exactly.

**Comment by shanyas10** [comment]
ah ok, got it!

**Comment by shanyas10** [comment]
@stephenbach I changed the choices as suggested. Also corrected the `choices_in_prompt` field for some prompts

**Review by stephenbach — APPROVED** [review]
Thanks, just a few minor fixes. Also changed the number indices in the choices to dashes, because the style guideline is to not use letters or numbers as indices if the target is the text itself (as opposed to the index).

**Pull request merged**
