### PR TITLE
clean cnn_dailymail

### PR DESCRIPTION
**Pull request by VictorSanh**

### CODE REVIEW

**Comment by Shashi456** [comment]
I did not want to open a new PR for this, but what do you think of the, "Can you write an outline of the article in a few points" and "Sum the article in brief", prompts? I was also going to mention this in #361 for the XSUM dataset

**Review by stephenbach — APPROVED** [review]
LGTM!

@Shashi456 they seem fine? What was your concern?

**Comment by Shashi456** [comment]
@stephenbach just additional prompt suggestions :)

**Comment by VictorSanh** [comment]
added your two suggestions @Shashi456! thank you!

**Comment by tianjianjiang** [comment]
BTW, just wandered #361 (#360) and wanted to know your option about the metrics: do we want to include BLEU for all summarization tasks? (I'm totally fine with it.)

**Comment by tianjianjiang** [comment]
@stephenbach Got it, thanks for the clarification!

**Pull request merged**
