### PR TITLE
prompts for amazon_reviews_multi and math_qa

### PR DESCRIPTION
**Pull request by manandey**

### CODE REVIEW

**Comment by stephenbach** [comment]
Thank you for the PR! Would you mind pulling `main` before we merge? We've just added some automatic checks for templates that we'd like to run.

**Comment by manandey** [comment]
> Thank you for the PR! Would you mind pulling `main` before we merge? We've just added some automatic checks for templates that we'd like to run.

Updated @stephenbach

**Review by stephenbach — CHANGES_REQUESTED** [review]
Thanks! You don't need to escape words like "stars" and "review." Escaping is only for words that affect the correctness of the output, which is usually class names. So, for example, you could replace "product category" with "type" and it would still be a sensible prompt.

**Comment by manandey** [comment]
> Thanks! You don't need to escape words like "stars" and "review." Escaping is only for words that affect the correctness of the output, which is usually class names. So, for example, you could replace "product category" with "type" and it would still be a sensible prompt.

Updated the changes, @stephenbach

**Review by stephenbach — APPROVED** [review]
Awesome, thank you! Please go ahead and update the spreadsheet!

**Pull request merged**
