### PR TITLE
add jp prompt for tydiqa

### PR DESCRIPTION
**Pull request by gentaiscool**
Japanese prompt for Tydiqa. @gentaiscool and @etsukokuste

I am following the design pattern of https://github.com/bigscience-workshop/promptsource/pull/766. Please let me know if it is acceptable.

### CODE REVIEW

**Comment by gentaiscool** [comment]
cc: @jungokasai

**Comment by VictorSanh** [comment]
@gentaiscool i merged the changes from `eval-hackathon` main branch to make the tests work.

Same as #766, i think it's best to separate the prompts for different languages.

Also, a bunch of the Japanese prompts don't compile (syntax errors), could you verify them please?

I am unable to read Japanese, so as soon as someone can verify these Japanese prompts, separate the languages and fix the syntax, we can merge!

**Comment by gentaiscool** [comment]
thanks @VictorSanh for reviewing. I will separate the prompts and check the errors :)

**Comment by afaji** [comment]
https://github.com/bigscience-workshop/promptsource/blob/62fad909efe3c4bf89aeee3e17d9bd56125c356e/promptsource/templates/tydiqa/primary_task/templates.yaml#L218
Screen Shot 2022-06-26 at 01 56 11

Hi @gentaiscool, I believe annotations.yes_no_question is either YES, NO, or NONE string, so the comparison should be with that, instead of comparing it with a Japanese string.

**Comment by gentaiscool** [comment]
> https://github.com/bigscience-workshop/promptsource/blob/62fad909efe3c4bf89aeee3e17d9bd56125c356e/promptsource/templates/tydiqa/primary_task/templates.yaml#L218
> 
> Screen Shot 2022-06-26 at 01 56 11
> 
> Hi @gentaiscool, I believe annotations.yes_no_question is either YES, NO, or NONE string, so the comparison should be with that, instead of comparing it with a Japanese string.

thanks for the suggestion @afaji. I made the changes accordingly.

**Comment by gentaiscool** [comment]
@VictorSanh we got the same issue as #766, the "show_new_templates / build" took more than 1 hour and the process got killed, since the prompts are larger now.

**Review by etsukokuste — APPROVED** [review]
Looks good to me!

**Comment by VictorSanh** [comment]
> @VictorSanh we got the same issue as #766, the "show_new_templates / build" took more than 1 hour and the process got killed, since the prompts are larger now.

I increased the timeout on the test workflow (and merged bach the changes from eval-hackathon)
Will wait for the tests to run, and merge if they pass!

**Comment by VictorSanh** [comment]
yes! merging now! thank you!

**Review by VictorSanh — APPROVED** [review]

**Pull request merged**
