### PR TITLE
Add scientific_papers templates

### PR DESCRIPTION
**Pull request by gchhablani**
**Notes**:
- I have only tested for `pubmed`. For `arxiv`, based on the dataset card, I believe it will be similar.
- The contexts might be too long for this to work nicely.

### CODE REVIEW

**Comment by craffel** [comment]
I think the abstract->section names task is somewhat ok... you also could do "Predict the first one hundred characters from the abstract" kind of task, or "predict the first sentence"?

**Comment by gchhablani** [comment]
I went for paragraphs and 100 words. The introduction is an expansion of the first few lines of the abstract, right? Is that doable?

**Comment by gchhablani** [comment]
@craffel
Can you please explain the test output?

**Comment by craffel** [comment]
Thanks!

**Comment by gchhablani** [comment]
@craffel
Thanks for reviewing and merging :)

**Pull request merged**
