### PR TITLE
Wiki bio

### PR DESCRIPTION
**Pull request by arunraja-hub**
@srush I have removed `article_title`

### CODE REVIEW

**Comment by srush** [comment]
@stephenbach also asked 

"can we make the desired output say that the information isn't contained for specific facts?"

Some sort of wording to tell the system it might not be possible to get everything right.

**Comment by arunraja-hub** [comment]
Yeah I haveadded the phrase `try to give details` in the comprehension template. Does that suffice?

**Comment by srush** [comment]
It says you have conflicts to fix?

**Comment by arunraja-hub** [comment]
@srush could you please help to merge this?

**Pull request merged**
