### PR TITLE
Add prompts for `samsum` dataset

### PR DESCRIPTION
**Pull request by cccntu**

### CODE REVIEW

**Comment by stephenbach** [comment]
Thank you for the PR! Would you mind pulling `main` before we merge? We've just added some automatic checks for templates that we'd like to run.

**Comment by stephenbach** [comment]
Whoops, looks like we're hitting an error for datasets that require special dependencies. Will fix later today. Please standby. 🙂

**Comment by cccntu** [comment]
Test failed because there is a an extra requirement: `pip install py7zr`

**Comment by stephenbach** [comment]
Blocked on #66 .

**Comment by stephenbach** [comment]
Ok, we're just adding deps as needed. Would you please pull main one more time?

**Comment by stephenbach** [comment]
Awesome, thank you! Please update the spreadsheet!

**Pull request merged**
